### ISSUE TITLE
Better support for cloud code

### ISSUE THREAD

**Issue by mnlbox** [bitnami/bitnami-docker-parse#43]
Hi guys,
Based on @andresbono guide in #41 I have suggest to add this to `bitnami-parse` docker image for support cloud code by default (without need to ):
I'm creating `cloud` directory in `/bitnami/parse` and put a dummy function there (in `main.js` file):
```
Parse.Cloud.define("hello", function(request, response) {
  response.success("Hi");
});
```
Then I create a symlink in  parse docker container with:
```
ln -s /bitnami/parse/cloud /opt/bitnami/parse/cloud
```
and also add `"cloud": "./cloud/main.js",` to `/bitnami/config.json` file.
No we can edit and run cloud code simply with edit `main.js` from my host.
I just suggest some hot reload rather than `nami restart parse` then we didn't need login to container and restart parse after each edit on my cloud code and can be automate all deployment process.

**/CC:** @javsalgar

**Comment by andresbono** [comment]
Thanks, we will take this into account. If you don't mind, I will close this issue but let's continue the conversation in the original issue: #41.
