### ISSUE TITLE
How to set fcm token to send push notification?

### ISSUE THREAD

**Issue by amirpiri** [bitnami/bitnami-docker-parse#44]
I need to send push notification and install parse dashboard but parse dashboard says:
Missing push configuration

**Comment by juan131** [comment]
You don't need to install Parse Dashboard on top of this Docker container. We already have a Parse Dashboard Image: https://github.com/bitnami/bitnami-docker-parse-dashboard

You can deploy both Parse & Parse Dashboard by running:

```
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-parse-dashboard/master/docker-compose.yml > docker-compose.yml
docker-compose up -d
```
