### ISSUE TITLE
server.js push notification settings

### ISSUE THREAD

**Issue by JHuenerberg** [bitnami/bitnami-docker-parse#47]
Hey folks,

Where can I edit the server.js file to get push notifications running?
Logged into the container with ```docker exec -it parse_1 bash``` but couldn't find any server.js file.
I already saw the issue #44 which doesn't help me. 

Thanks ✌️

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        e68fc7a
 Built:             Tue Aug 21 17:21:31 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:29:02 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 18.06.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.93-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 6
Total Memory: 2.933GiB
Name: linuxkit-025000000001
ID: SJGR:P4UT:HVXR:2GB2:WQQV:3QEQ:5BBW:BIER:QD6Z:2FNW:U3EH:KFLF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 54
 Goroutines: 73
 System Time: 2018-11-06T13:53:37.969909428Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.4.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2o  27 Mar 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC

**Comment by rafariossaa** [comment]
Hi @JHuenerberg ,
  Could you provide further information ? For example if you are following any guide for what you want to do, if you are running it with docker-compose or just with docker, etc.

Thanks forehand.
Rafael Rios

**Comment by JHuenerberg** [comment]
Hey @rafariossaa ,
I'm just following the [Parse Dokumentation for Push Notifications](https://docs.parseplatform.org/parse-server/guide/#push-notifications). The docker container runs parse server inside node. And somewhere there ist the parse server initialized.  

`var server = new ParseServer({});`

**Comment by JHuenerberg** [comment]
Hi @rafariossaa ,
Thanks for the reply. The Bitnami docker image sets some [environment-variables](https://github.com/bitnami/bitnami-docker-parse#environment-variables). Thats the location where the API Key needs to be set for push notification, beside the existing variables. I just need to edit this file a bit.

Thanks for helping me out.
