### ISSUE TITLE
Enable S3 Adapter

### ISSUE THREAD

**Issue by dan-burt** [bitnami/bitnami-docker-parse#53]
**Description**

I would like to enable the S3 adapter within the container image. In the base parse-server's Definition.js file, the following parameter is defined:

```
filesAdapter: {
    env: 'PARSE_SERVER_FILES_ADAPTER',
    help: 'Adapter module for the files sub-system',
    action: parsers.moduleOrObjectParser,
  }
```

But I do not know what values are required, how to configure it to point to my S3 bucket and / or any files that are required in the folder structure.

**Version**

```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
- Output of `docker info`:
```

```
Server:
 Containers: 26
  Running: 26
  Paused: 0
  Stopped: 0
 Images: 40
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-33-generic
 Operating System: Ubuntu 16.04.6 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.667GiB
 Name: jingoserver
 ID: IVTG:CNZ5:46ZO:3XZS:S6IK:UY3X:WTHE:3O75:CO6S:HNTI:ZSFL:DH56
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: danburt
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880fe
docker-py version: 3.4.1
CPython version: 3.6.6
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```

**Comment by rafariossaa** [comment]
Hi @dan-burt ,
  Could you elaborate a little bit more ? It seems that the message was cut when you were to indicate the parameters.

**Comment by dan-burt** [comment]
Apologies, the item saved while I was still inputing the details in.

**Comment by dan-burt** [comment]
I have tried to add new environment variables into my docker-compose.yml file, following the guide located at:

[http://docs.parseplatform.org/parse-server/guide/#configuring-file-adapters](http://docs.parseplatform.org/parse-server/guide/#configuring-file-adapters)

But the container crashes on startup. Repeating again from opening post, I don't know the value and / or values that are expected.

This was the config from my latest (failed) attempt:
```
      - PARSE_SERVER_FILES_ADAPTER=s3-files-adapter
      - S3_ACCESS_KEY=access_key
      - S3_SECRET_KEY=secret_key
      - S3_BUCKET=bucket_name
      - S3_REGION=eu-west-2
      - S3_BUCKET_PREFIX=test1338
      - S3_DIRECT_ACCESS=true

```

**Comment by dan-burt** [comment]
Knew it was a simple syntax issue... ha!

Got the hint I was looking for at the following link:
[https://github.com/parse-community/parse-server-s3-adapter/blob/master/README.md#using-environment-variables](https://github.com/parse-community/parse-server-s3-adapter/blob/master/README.md#using-environment-variables)

The correct syntax is:
`      - PARSE_SERVER_FILES_ADAPTER="@parse/s3-files-adapter"`

This also corresponds to the name of a directory within the Parse installation, which I expect matches strings:
`/opt/bitnami/parse/node_modules/@parse/s3-files-adapter`

The other environment variables were correct, and I am able to upload files to S3.
