### ISSUE TITLE
SendGrid email

### ISSUE THREAD

**Issue by dan-burt** [bitnami/bitnami-docker-parse#54]
**Description**

Is SendGrid adapter installed by default? How or where do I check?
If not, how do I install extra adapters within the Bitnami Docker container for Parse server?

**Comment by Mauraza** [comment]
Hi @dan-burt,

SendGrid is not installed by default. You can follow the documentation of [parse to install,](https://docs.parseplatform.org/parse-server/guide/#cloud-modules) in this case you should to use persistence to keep the data. 
Maybe this link it's useful https://github.com/bitnami/bitnami-docker-parse#how-to-deploy-your-cloud-functions-with-parse-cloud-code

**Comment by dan-burt** [comment]
I'm not sure I understand. You are providing links for "Cloud Code" which is custom JS code.

I need to install the SendGrid module. I believe that on a manual server / host, I would issue "nom install sendgrid" or similar at the terminal. However, in a container world, I dont believe it occurs the same way, and I would also like to use publicly published & maintained images with as much inclusive configuration out of the box.

**Comment by Mauraza** [comment]
Maybe for you the answer could use the base this image and add the modules do you want. 
you can do it create a Dockerfile:
```
FROM bitnami/parse:latest
USER root
RUN cd /opt/bitnami/parse 
RUN npm i -g sendgrid
USER 1001
```
I this way you have an image updated and configuration for your solution.
