### ISSUE TITLE
Support for Live Queries?

### ISSUE THREAD

**Issue by mrvnklm** [bitnami/bitnami-docker-parse#56]
It seems like there is no support for Live Queries, are you going to add this functionality in near future?

**Comment by carrodher** [comment]
Hi, thanks for the suggestions, it is something that was on our radar but as we are a small team with different priorities I can't provide you an ETA for this addition. Anyways, I just created an internal task to evaluate this feature and work on it when we have some bandwidth.

**Comment by mrvnklm** [comment]
I would look into creating a PR, but I can't find the base image which includes the express server configuration.

**Comment by carrodher** [comment]
Hi, thanks for trying to create the PR; unfortunately this application is still using an internal logic called `nami` (NodeJS at the end). We are migrating this logic to bash and adding it to the public GH repositories but as there are several assets we are doing it little by little being Parse one of the ones still using the private appraoch

**Comment by carrodher** [comment]
Unfortunately, once evaluating the request, due to other priorities there are no plans in the short term to add this feature
