### ISSUE TITLE
about run the docker

### ISSUE THREAD

**Issue by zero16832** [bitnami/bitnami-docker-parse#59]
### Name and Version

parse server

### What is the problem this feature will solve?

hi,thank your project,and can make a video to tell how to run the docker with parse? I just use the parse with this docker,but it can't run it,thank for your help.

### What is the feature you are proposing to solve the problem?

make video about how to use it.

### What alternatives have you considered?

make video about how to use it.

**Comment by javsalgar** [comment]
Hi,

Did you try following these instructions? https://github.com/bitnami/bitnami-docker-parse#docker-compose

**Comment by zero16832** [comment]
yes,i just following this to test it.but in docker ,it tips not user in db?can you make a video to tall me how to use it?

**Comment by javsalgar** [comment]
Hi,

If you are a beginner, then maybe you should try with parse dashboard:

```
curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-parse-dashboard/master/docker-compose.yml > docker-compose.yml
docker-compose up
```

Then access 127.0.0.1 with credentials user - bitnami

![image](https://user-images.githubusercontent.com/1133777/162158379-d6f24b56-dbb9-44eb-9cb4-60a826e46550.png)

**Comment by zero16832** [comment]
can't I run it whit docker desktop on windows 10?

**Comment by javsalgar** [comment]
Yes you should be able, did you install docker-compose ? https://docs.docker.com/compose/install/

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami parse container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by zero16832** [comment]
I JUST FINISH RUN IT TO Windows Docker!It need to set - PARSE_DASHBOARD_PARSE_HOST=127.0.0.1 In parse-dashboard.
another quest it? how to set up the cloud code in parse? i follow the document,but it fail.it saw,can't not find the model. “/cloud/main.js”
